config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :tips
  resources :notes
  resources :topics
  resources :frameworks do
    resources :topics, module: :frameworks do
      resources :notes, module: :topics do
        resources :tips, module: :notes
      end
    end
  end
  root to: 'frameworks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :topic
  has_many :tips, dependent: :destroy
end

app/controllers/frameworks/topics/notes/tips_controller.rb
class Frameworks::Topics::Notes::TipsController < TipsController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

end

app/controllers/frameworks/topics/notes_controller.rb
class Frameworks::Topics::NotesController < NotesController
  before_action :set_topic, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to framework_topic_path(@note.topic.framework.id, @note.topic.id), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :details, :topic_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.slim
= simple_form_for @note do |f|
    = f.input :name
    = f.input :details
    = f.input :topic_id, as: :hidden, input_html: {value: @topic.id}
    = f.submit

app/views/notes/edit.html.slim
h1 Editing note

== render 'form'

= link_to 'Show', @note
'  |
= link_to 'Back', notes_path

app/views/notes/index.html.slim
h1 Listing notes

table.table
  thead
    tr
      th Name
      th Details
      th Topic
      th
      th
      th

  tbody
    - @notes.each do |note|
      tr
        td = note.name
        td = note.details
        td = note.topic
        td = link_to 'Show', framework_topic_note_path(@topic.framework.id, @topic.id, note)
        td = link_to 'Edit', edit_framework_topic_note_path(@topic.framework.id, @topic.id, note)
        td = link_to 'Destroy', framework_topic_note_path(@topic.framework.id, @topic.id, note), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Note', new_framework_topic_note_path(@topic.framework.id, @topic.id)

app/views/notes/new.html.slim
h1 New note

== render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.slim
p#notice = notice
h1
  = @note.topic.name
h3 = @note.name
p
  strong  = @note.details

- @note.tips.each do |tip|
  .panel.panel-black.col-md-12
    h4 = tip.name
    hr
    = raw tip.text
    br
    - tip.try(:pictures).each do |picture|
      = image_tag picture.picture, width: "100%"
.col-md-12.panel.panel-black
  .p10
    = simple_form_for Tip.new, html: {multipart: true}  do |f|
      = f.input :name, input_html:{class: "form-control"}
      = f.trix_editor :text, input_html:{class: "form-control mt20"}
      = f.input :note_id, as: :hidden, input_html:{value: @note.id}
      = file_field_tag "tip[picture][]", type: :file, multiple:true
      = f.submit 'Submit', class:"btn btn-primary mt10"