config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :tips
  resources :notes
  resources :topics
  resources :frameworks do
    resources :topics, module: :frameworks do
      resources :notes, module: :topics do
        resources :tips, module: :notes
      end
    end
  end
  root to: 'frameworks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :framework
  has_many :notes, dependent: :destroy

end

app/controllers/frameworks/topics/notes/tips_controller.rb
class Frameworks::Topics::Notes::TipsController < TipsController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

end

app/controllers/frameworks/topics/notes_controller.rb
class Frameworks::Topics::NotesController < NotesController
  before_action :set_topic, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

end

app/controllers/frameworks/topics_controller.rb
class Frameworks::TopicsController < TopicsController
  before_action :set_framework

  # GET /topics
  # GET /topics.json
  def index
    @topics = @framework.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_framework
      @framework = Framework.find(params[:framework_id])
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to framework_path(@topic.framework.id), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :framework_id, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.slim
= simple_form_for @topic do |f|
    = f.input :name
    = f.input :framework_id, as: :hidden, input_html:{value: @framework.id}
    = f.input :description
    = f.submit

app/views/topics/edit.html.slim
h1 Editing topic

== render 'form'

= link_to 'Show', @topic
'  |
= link_to 'Back', topics_path

app/views/topics/index.html.slim
h1 Listing topics

table
  thead
    tr
      th Name
      th Framework
      th Description
      th
      th
      th

  tbody
    - @topics.each do |topic|
      tr
        td = topic.name
        td = topic.framework
        td = topic.description
        td = link_to 'Show', topic
        td = link_to 'Edit', edit_topic_path(topic)
        td = link_to 'Destroy', topic, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.slim
h1 New topic

== render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.slim
.row
  .col-md-12
    p#notice = notice

    h2
      = @topic.name
    p
      = @topic.description
.row
  - @topic.notes.each do |note|
    .col-md-4
      .panel.panel-black.panel-bg
        .p30
          h3 = link_to note.name, framework_topic_note_path(@topic.framework.id, @topic.id, note)
          p = raw note.details
.row
  .col-md-12
    = simple_form_for Note.new do |f|
        = f.input :name
        = f.trix_editor :details
        = f.input :topic_id, as: :hidden, input_html: {value: @topic.id}
        = f.submit