config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :tips
  resources :notes
  resources :topics
  resources :frameworks do
    resources :topics, module: :frameworks do
      resources :notes, module: :topics do
        resources :tips, module: :notes
      end
    end
  end
  root to: 'frameworks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/framework.rb
class Framework < ApplicationRecord
  has_many :topics, dependent: :destroy
end

app/controllers/frameworks/topics/notes/tips_controller.rb
class Frameworks::Topics::Notes::TipsController < TipsController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

end

app/controllers/frameworks/topics/notes_controller.rb
class Frameworks::Topics::NotesController < NotesController
  before_action :set_topic, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

end

app/controllers/frameworks/topics_controller.rb
class Frameworks::TopicsController < TopicsController
  before_action :set_framework

  # GET /topics
  # GET /topics.json
  def index
    @topics = @framework.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_framework
      @framework = Framework.find(params[:framework_id])
    end

end

app/controllers/frameworks_controller.rb
class FrameworksController < ApplicationController
  before_action :set_framework, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /frameworks
  # GET /frameworks.json
  def index
    @frameworks = Framework.all
  end

  # GET /frameworks/1
  # GET /frameworks/1.json
  def show
  end

  # GET /frameworks/new
  def new
    @framework = Framework.new
  end

  # GET /frameworks/1/edit
  def edit
  end

  # POST /frameworks
  # POST /frameworks.json
  def create
    @framework = Framework.new(framework_params)

    respond_to do |format|
      if @framework.save
        format.html { redirect_to @framework, notice: 'Framework was successfully created.' }
        format.json { render :show, status: :created, location: @framework }
      else
        format.html { render :new }
        format.json { render json: @framework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frameworks/1
  # PATCH/PUT /frameworks/1.json
  def update
    respond_to do |format|
      if @framework.update(framework_params)
        format.html { redirect_to @framework, notice: 'Framework was successfully updated.' }
        format.json { render :show, status: :ok, location: @framework }
      else
        format.html { render :edit }
        format.json { render json: @framework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frameworks/1
  # DELETE /frameworks/1.json
  def destroy
    @framework.destroy
    respond_to do |format|
      format.html { redirect_to frameworks_url, notice: 'Framework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_framework
      @framework = Framework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def framework_params
      params.require(:framework).permit(:name, :active, :position)
    end
end

app/helpers/frameworks_helper.rb
module FrameworksHelper
end

app/views/frameworks/_form.html.slim
= form_for @framework do |f|
  - if @framework.errors.any?
    #error_explanation
      h2 = "#{pluralize(@framework.errors.count, "error")} prohibited this framework from being saved:"
      ul
        - @framework.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :position
    = f.number_field :position
  .actions = f.submit

app/views/frameworks/edit.html.slim
h1 Editing framework

== render 'form'

= link_to 'Show', @framework
'  |
= link_to 'Back', frameworks_path

app/views/frameworks/index.html.slim
.container-fluid
  .row
    .col-lg-12
      h1 Simple Sidebar
      p This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.

    .panel.col-md-4.panel-success
      h3 New framework
      = simple_form_for Framework.new do |f|
        = f.input :name
        = f.input :active
        = f.input :position
        .actions = f.submit

app/views/frameworks/new.html.slim
h1 New framework

== render 'form'

= link_to 'Back', frameworks_path

app/views/frameworks/show.html.slim
p#notice = notice
.row
  .col-md-12.mb30.pull-right
    = link_to 'new topic', new_framework_topic_path(@framework.id), class:"btn btn-primary"
.row
  - @framework.topics.each do |topic|
    .col-md-4
      .panel.panel-black.panel-bg
        .p30
          h2
            = link_to topic.name, framework_topic_path(@framework, topic)
          p = topic.description